.TH JSONBOT 1 "7 Nov 2010" "Debian GNU/Linux" "jsb manual"
.SH NAME
.B jsb-gozerimport \- The JSONBOT gozerimport program
.SH SYNOPSIS
JSONBOT is a remote event-driven framework for building bots that talk JSON
to each other over XMPP. 
.B jsb-gozerimport
is used to import datafiles from GOZERBOT into JSONBOT.  
.B 
.SH "DESCRIPTION"
.P
GOZERBOT was there before JSONBOT and to provide GOZERBOT users to upgrade
to JSONBOT this program is provided
.PP
.SH USAGE
.P
.B Usage: jsb-gozerimport <gozerdatadir> <outputdir>
.SH "DOCUMENTATION"
See http://jsonbot.org or http://jsonbot.appspot.com/docs for more documentation

.SH "SEE ALSO"
jsonbot(1)

.SH AUTHOR
This manual page was written by Bart Thate <bthate@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
